### ISSUE TITLE
Circle skips pulse animation

### ISSUE THREAD

**Issue by RaketeOriginal** [SloppyDesigns/target-ui#2]
Hey .. if im hovering a prop or target with the circle, it skips the animation and goes straight to the circle with the X .. even without rightlclick 

any idea?

https://cdn.discordapp.com/attachments/918469925113303041/1136732755703632042/image.png

**Comment by RaketeOriginal** [comment]
And can you tell me, where i can change the icon color :) ? thx

**Comment by SloppyShovel** [comment]
Which pulse animation, there is no pulse animation, also what target ?

**Comment by RaketeOriginal** [comment]
i saw your design in a youtube video - he made a tutorial and a showcase of your design .. 

Here: 
https://youtu.be/-SnL1AgJUNI?t=113 

we use qb-target

sorry for asking so much stuff .. but is it possible to set the first target option als on the right side? atm its left

![image](https://github.com/SloppyDesigns/target-ui/assets/110101558/220f8d78-7d8f-4a9e-844b-981060ffe604)


P.S. i got the icon color :) - so i make the design match our CI

![image](https://github.com/SloppyDesigns/target-ui/assets/110101558/e961ecb0-5159-48d1-a457-dfed1424065c)
