### ISSUE TITLE
Target is invisible

### ISSUE THREAD

**Issue by newbialywhodis** [SloppyDesigns/target-ui#3]
After the new update ox_target, unfortunately, the entire target is invisible. How can this be fixed?

**Comment by SloppyShovel** [comment]
Make sure you grab the latest version that added support for the overlapping zones and that you are using the latest ox_target

**Comment by newbialywhodis** [comment]
Yeah, i just downloaded newest release of ox_target, i have put your web into its web and it doesnt work

**Comment by SloppyShovel** [comment]
make sure you overwrite the folders not delete them, and restart your server

**Comment by newbialywhodis** [comment]
overwrite? soo i cant just remove web folder from ox, and place yours?

**Comment by SloppyShovel** [comment]
No you have to overwrite them, cause it doesn't supply all files only to change the design, its in the instructions on the readme

**Comment by newbialywhodis** [comment]
but i have to put web in ox_target, and confirm override files? or delete all files from web and put them

**Comment by SloppyShovel** [comment]
https://github.com/SloppyDesigns/target-ui#installation

**Comment by SloppyShovel** [comment]
override yes if you delete it, it will not work

**Comment by SloppyShovel** [comment]
All good now, good to close ?
