### ISSUE TITLE
In the new versions of ox_target, some options doesn't show up

### ISSUE THREAD

**Issue by b-bgomes** [SloppyDesigns/target-ui#4]
![image](https://github.com/SloppyDesigns/target-ui/assets/97984058/ceaf665a-f0db-48d5-8aaf-cf9f6c3e2dc9)
![image](https://github.com/SloppyDesigns/target-ui/assets/97984058/af39b8bb-902e-4344-a0fb-950d776b5762)

**Comment by SloppyShovel** [comment]
That is not related to the UI, script related either job check or something with canInteract UI works fine

**Comment by b-bgomes** [comment]
> That is not related to the UI, script related either job check or something with canInteract UI works fine

But if i job update still the same... i don't know with the changes, need some update.

**Comment by SloppyShovel** [comment]
Oke but that  has nothing to do with the target UI, the target UI works fine, if 1 option shows, all of them will work
